/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'mperry' at '10/06/14 5:30 PM' with Gradle 1.11
 *
 * @author mperry, @date 10/06/14 5:30 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
