/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'MarkPerry' at '13/12/13 4:00 PM' with Gradle 1.9
 *
 * @author MarkPerry, @date 13/12/13 4:00 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
