/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'mperry' at '10/06/14 5:30 PM' with Gradle 1.11
 *
 * @author mperry, @date 10/06/14 5:30 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
